language: python

# for container-y googdness:
sudo: false

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

# command to install dependencies
install: "pip install --pre -e .[test]"

# command to run tests, e.g. python setup.py test
script: nosetests

after_success:
  - coveralls
