language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"

# command to install dependencies
install: "pip install -r mock manual zope.component"

# command to run tests, e.g. python setup.py test
script: nosetests
